### ISSUE TITLE
Reconsider pull bot

### ISSUE THREAD

**Issue by isabelroses** [auxolotl/nixpkgs#7]
With the most recent [pull bot PR](https://github.com/auxolotl/nixpkgs/pull/6) we have had some issues with merging the PR since it has merge conflicts and this is only going to get worse.

Therefore we should consider alternatives. I prepose
Renovate - https://docs.renovatebot.com

**Comment by Sorixelle** [comment]
For now, I'll manually create a branch to resolve the conflicts, so we can get the bump unblocked.

**Comment by Sorixelle** [comment]
I think the Pull bot created a merge commit to bring in the last update. That's... annoying, because now we have Nixpkgs on top of ours - we want to avoid that.

Does anyone have any suggestions there? My git-fu isn't strong enough to come up with a clean solution here, other than "force push a properly rebased branch to master", which I would rather not set precedent for.

**Comment by isabelroses** [comment]
> I think the Pull bot created a merge commit to bring in the last update. That's... annoying, because now we have Nixpkgs commits on top of ours - we want to avoid that.

I think its probably fine but annoying yes

> Does anyone have any suggestions there? My git-fu isn't strong enough to come up with a clean solution here, other than "force push a properly rebased branch to master", which I would rather not set precedent for.

AFIK pull bot brings in all changes until it is mergeable at which point it merges itself???
The only issue is what if upstream introduces merge conflicts then do they fix it or do we have to manually resolve it.

**Comment by Sorixelle** [comment]
[Here's the diff](https://github.com/auxolotl/nixpkgs/compare/nixpkgs-bump-2024-05-03?expand=1) for an example of the issue I'm mentioning - notice how these two branches are unmergeable due to conflicts. I'm not sure now to resolve this one.

**Comment by isabelroses** [comment]
> > [Here's the diff](https://github.com/auxolotl/nixpkgs/compare/master...auxolotl:nixpkgs:nixpkgs-bump-2024-05-03?expand=1) for an example of the issue I'm mentioning - notice how these two branches are unmergeable due to conflicts. I'm not sure now to resolve this one.
> 
> taking a look, it seems like it was caused by upstream ill try fix it.

https://github.com/auxolotl/nixpkgs/pull/8

**Comment by isabelroses** [comment]
I went and closed the PR since the pull bot PR was getting really messy, hopefully that should resolve itself.

**Comment by getchoo** [comment]
>  That's... annoying, because now we have Nixpkgs commits on top of ours - we want to avoid that.

there isn't a good way around this, as it's rebasing is inherently rewriting history. an alternative here could be squash commits...though that would really mess up our git blame and ability to bisect (the latter would matter less ig, as it'd be issues from nixpkgs, not us)

in general, i also don't think we need a bot or anything fancy here. a workflow like this could work (and easily be extended to work across multiple branches in a matrix)
```yaml
name: Sync with nixpkgs

on:
  schedule:
     - cron: '0 * * * *' # every hour
  workflow_dispatch:

jobs:
  sync:
    name: Fetch & sync

    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    env:
      CURRENT_BRANCH: ${{ github.ref_name }}
      NIXPKGS_BRANCH: nixpkgs-${{ github.ref_name }}
      PR_BRANCH: merge-nixpkgs-${{ github.ref_name }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Git user info
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Create new branch
        run: |
          git switch -c "$PR_BRANCH"

      - name: Fetch upstream nixpkgs
        run: |
          git origin add fork https://github.com/NixOS/nixpkgs.git
          git fetch fork "$CURRENT_BRANCH":"$NIXPKGS_BRANCH"

      - name: Merge commits
        run: |
          git merge "$NIXPKGS_BRANCH"

      - name: Push to branch
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if ! git diff --color=always --exit-code origin/"$CURRENT_BRANCH"; then
            git fetch origin "$PR_BRANCH" || true
            git push --force-with-lease -u origin "$PR_BRANCH"
          fi

      - name: Create pull request if needed
        run: |
          open_prs="$(gh pr list --base "$CURRENT_BRANCH" --head "$PR_BRANCH" | wc -l)"
          if [ "$open_prs" -eq 0 ]; then
            gh pr create \
              --base "$CURRENT_BRANCH" \
              --head "$PR_BRANCH" \
              --title: "sync with nixpkgs/$CURRENT_BRANCH $(date '+%Y %m %d')" \
              --fill
          fi
```
